services:
  db:
    image: postgres:15
    container_name: marketplace_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=marketplace
      - POSTGRES_USER=marketplace_admin
      - POSTGRES_PASSWORD=0312
    # ports:
    #   - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: marketplace_redis
    # ports:
    #   - "6379:6379"

  web:
    build: .
    container_name: marketplace_web
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "4545:8000"
    env_file: .env
    depends_on:
      - db
      - redis
    environment:
      - PYTHONPATH=/app:/app/apps

  worker:
    build: .
    container_name: marketplace_worker
    command: celery -A core worker -l info
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - redis
      - db
      - web
    environment:
      - PYTHONPATH=/app

  beat:
    build: .
    container_name: marketplace_beat
    command: celery -A core beat -l info
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - redis
      - db
      - web
    environment:
      - PYTHONPATH=/app

volumes:
  postgres_data:

  